project:
  type: website
  output-dir: docs
  resources: "/img"

website:
  title: "Madeline G. Eppley"
  navbar:
    right: 
      - icon: github
        href: https://github.com/madeline-eppley
      - icon: twitter
        href: https://twitter.com/MadelineGEppley
      - icon: linkedin
        href: https://www.linkedin.com/in/madeline-eppley/
      - icon: mortarboard-fill
        href: https://cos.northeastern.edu/people/madeline-eppley/
        
    left:
      - href: index.qmd
        text: Home
      - href: phd_work.qmd
        text: Research
      - href: outreach.qmd
        text: Outreach
      - href: scicomm.qmd
        text: SciComm
      - href: resume.qmd
        text: Resume
      - href: gallery.qmd
        text: Travel
  page-footer: 
    left: "Copyright 2024, Madeline Eppley"
    right: "Made with Quarto"
    border: true

format:
  html:
    theme: lux
    mainfont: 'Tahoma'
    toc: true
    page-layout: full

editor: visual

