project:
  type: website
  output-dir: docs
  resources: "/img"

website:
  title: "Madeline G. Eppley"
  navbar:
    right: 
      - icon: github
        href: https://github.com/madeline-eppley
      - icon: cloud
        href: https://bsky.app/profile/madeline-eppley.bsky.social 
      - icon: linkedin
        href: https://www.linkedin.com/in/madeline-eppley/
      - icon: mortarboard-fill
        href: https://cos.northeastern.edu/people/madeline-eppley/
      - icon: laptop
        href: https://www.madeline-eppley.com
        
    left:
      - href: index.qmd
        text: Home
      - href: labnotebook.qmd
        text: Lab Notebook
      - href: coding.qmd
        text: Coding and Bioinfomatics
      - href: resources.qmd
        text: Resources

  page-footer: 
    left: "Copyright 2024, Madeline Eppley"
    right: "Made with Quarto"
    border: true

  twitter-card: true

format:
  html:
    theme: lux
    mainfont: 'Tahoma'
    toc: true
    page-layout: full

editor: visual

