---
title: "Resources"
---

## STEM Education Resources

## Science Communication Resources

### Personal Academic Websites

###### Choosing where to build and host your website

(@) **GitHub + Quarto Website**
- Pros/Cons: I have used GitHub and Quarto to build this website! You need a GitHub account and some intermediate familiarity with coding in R to build your own. There is no cost to host your site, and you can host it on any custom domain that you may own. I have found that design functionality is extremely limited unless you are willing to custom-develop your own styles.css documents, which is time-consuming. Importantly, you can only host one GitHub pages site per account. 

- I have a tutorial on how to build your own Quarto website and host it on GitHub! Find it on my Coding page. To get started, Quarto also has a lot of information [here](https://quarto.org/docs/websites/).

(@) **Weebly** 
- Pros/Cons: I have used Weebly to build my personal website! I really enjoyed the ease of use and multitude of design options with Weebly. It is free to host your website with a '.weebly.com' address, but you can also host on any custom domain that you may own. I purchased my custom domain through Weebly, and it was easy. There is a cost to remove banner ads at the bottom of your page, but they aren't too distracting if you want to keep it free. No coding experience required, but it is helpful to know how to insert custom .html to embed code and links. 

- You can find my personal website on Weebly [here](https://www.madeline-eppley.com).

(@) **Google Sites**
- Pros/Cons: Google sites are free with a Google account and don't require any coding experience to build! My lab has a google-hosted website that I edit regularly, and I find it easy with great version-control to use as a review process before you publish. Your site is hosted on a 'sites.google.com/site/yourwebsitenamehere address', or you can use any custom domain that you may own. There is decent flexibility with design and they have pre-made templates that can get you started. I have heard that some algorithms may filter google sites out of web browser search results, but have not come across this issue (potentially because I use Chrome).

(@) **Other Hosting Options - Squarespace, Wix, WordPress**
- Pros/Cons: I have not built websites with any other hosting service. I have peers that have successfully used Squarespace, Wix, and WordPress with mixed reviews. Most of these hosting services will require you to pay for a plan or to remove advertisements. You may also need to purchase a custom domain, but some, like WordPress, may allow you to host for free with a '.wordpress.com' address.   

## LGBTQIA+ in STEM Resources
