project:
  type: website
  output-dir: docs
  resources: "/img"

website:
  site-url: "https://madeline-eppley.github.io/"
  title: "Madeline Eppley"
  navbar:
    logo: img/crablogo.jpg
    right: 
      - icon: github
        href: https://github.com/madeline-eppley
      - icon: twitter
        href: https://twitter.com/MadelineGEppley
      - icon: linkedin
        href: https://www.linkedin.com/in/madeline-eppley/
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About Me
      - href: phd_work.qmd
        text: My Work
      - href: gallery.qmd
        text: Gallery
      - href: resume.qmd
        text: Resume
  page-footer: 
    left: "Copyright 2023, Madeline Eppley"
    right: "Made with Quarto"

format:
  html:
    theme: solar
    mainfont: 'Montserrat'
    css: styles.css
    toc: true
    page-layout: full

editor: visual

