project:
  type: website
  output-dir: docs

website:
  title: "Madeline Eppley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    contents:
      - section: "About Me"
        contents:
          - about_me.qmd
      - section: "Research"
        contents:
          - phd_work.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

